version: "3"
services:
  get_all_message_from_slack:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: get_all_message_from_slack-image
    container_name: get_all_message_from_slack-container
    tty: true
    env_file: .env # shellスクリプト内でも環境変数として使用するため
